### ISSUE TITLE
URL Parameters

### ISSUE THREAD

**Issue by nVisium-Kevin-Cody** [FrUh/ExtendedMacro#2]
I am attempting to utilize the Extraction Configuration to replace a value within the URL (REST style API), but the replace configuration fails to recognize the selection within the URL. Is this a known issue or a bug than can help overcome?

**Comment by nVisium-Kevin-Cody** [comment]
*correction* The URL parameters are updated per the Extended Macro rule, but Intruder does not update the URL within the Intruder Attack Window, thus it looks as if the macro fails.

Looking at the Extended Macro log confirms that the updates are indeed taking place. Additionally, I proxied Burp through another upstream proxy to confirm.

**Comment by fruh** [comment]
I am not sure if i understood well, so is it okay? did you mean, that the change is not visible in the intruder window (the change is visibile only in the logger)?

**Comment by nVisium-Kevin-Cody** [comment]
Correct. I am replacing a value within the URL path (REST style parameter) with a value obtained from the Extended Macro. Although the macro does work, the actual URL shown within the Intruder window is never updated with this value. The only way to know it worked is by looking at the Extended Macro Logger (or via upstream proxy).
